### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by jlogan03**
https://materials.readthedocs.io/en/latest/

Sign moi

Technically changes only to comments and requirements, plus a minor bug fix

edit: and also everything on the branch that added copper and NIST polynomials

### CODE REVIEW

**Comment by mvernacc** [comment]
I am going to put on my "stickler for good git workflows" hat:
I don't like dog-piling this on top of the NIST polynomials PR (#3 ).

Gameplan:
 - If you found the NIST polynomials useable, I will close and merge #3. If there are any changes you discovered that you want, I will fix those before merging.
- After that, you rebase `docs` onto `master`
- Then I review and merge this PR.

**Comment by mvernacc** [comment]
I am excited to have docs :D

**Comment by jlogan03** [comment]
Yeah, agree. When I switched over to the new branch, I had checked out master and  did git reset --hard, but must have missed something. The bundling was definitely not intentional

**Comment by jlogan03** [comment]
And yes, the NIST poly branch is quite useable. I think it would be good to have density properties as well, but I'm surviving just fine setting density manually for now.

**Pull request merged**
